//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicIndustryConcerts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artists
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artists()
        {
            this.Concerts = new HashSet<Concerts>();
        }
    
        public int ArtistID { get; set; }
        public string ArtistName { get; set; }
        public string MusicGenre { get; set; }
        public decimal PerformancePrice { get; set; }
        public bool ExplicitContent { get; set; }
        public bool ArtistAvailability { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Concerts> Concerts { get; set; }
    }
}
