//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicIndustryConcerts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concerts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Concerts()
        {
            this.TicketOrders = new HashSet<TicketOrders>();
        }
    
        public int ConcertID { get; set; }
        public System.DateTime EventDate { get; set; }
        public int PlaceID { get; set; }
        public int ArtistID { get; set; }
        public decimal BaseTicketPrice { get; set; }
        public decimal VIPTicketPrice { get; set; }
        public int RemainingCapacity { get; set; }
    
        public virtual Artists Artists { get; set; }
        public virtual Places Places { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketOrders> TicketOrders { get; set; }
    }
}
