//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicIndustryConcerts
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MusicIndustryConcertsEntities : DbContext
    {
        public MusicIndustryConcertsEntities()
            : base("name=MusicIndustryConcertsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artists> Artists { get; set; }
        public virtual DbSet<Concerts> Concerts { get; set; }
        public virtual DbSet<Places> Places { get; set; }
        public virtual DbSet<TicketOrders> TicketOrders { get; set; }
    }
}
