//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicIndustryConcerts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Places
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Places()
        {
            this.Concerts = new HashSet<Concerts>();
        }
    
        public int PlaceID { get; set; }
        public string PlaceName { get; set; }
        public int Capacity { get; set; }
        public bool BarArea { get; set; }
        public bool VIPArea { get; set; }
        public int OpeningHour { get; set; }
        public int ClosingHour { get; set; }
        public bool AdultsOnly { get; set; }
        public decimal RentalPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Concerts> Concerts { get; set; }
    }
}
