//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicIndustryConcerts
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketOrders
    {
        public int OrderID { get; set; }
        public int ConcertID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool VIPTicket { get; set; }
        public string Mail { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual Concerts Concerts { get; set; }
    }
}
